language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.2.0
  matrix:
    - NGINX_VER=1.15 TAGS=1.15,1,latest
    - NGINX_VER=1.14 TAGS=1.14
    - NGINX_VER=1.13 TAGS=1.13

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
