language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=1.13
  matrix:
    - TAG=1.13 NGINX_VER=1.13 EXTRA_TAG=1
    - TAG=1.12 NGINX_VER=1.12

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
